DB_NAME = "defaultdb"
DB_USER = "postgres"

SESSIONSDB_HOST = '127.0.0.1'
SESSIONSDB_PORT = 6379
SESSIONSDB_PASSWD = None
SESSIONSDB_NO = 1

# SMTP
MD_HOST = '127.0.0.1'
MD_PORT = 10000
MD_USERNAME = None
MD_KEY = ''


class API_LOGGER:
    ENABLED = False
