DB_NAME = "defaultdb"
DB_USER = "postgres"

SESSIONSDB_HOST = "127.0.0.1"
SESSIONSDB_PORT = 6379
SESSIONSDB_PASSWD = None
SESSIONSDB_NO = 1

# SMTP
SMTP_HOST = "127.0.0.1"
SMTP_PORT = 10000
SMTP_USERNAME = None
SMTP_KEY = ""


class API_LOGGER:
    ENABLED = False
